### ISSUE TITLE
setImmediate.js:13 Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by ToyCon** [codestates/cocodus#120]
### 어떤 에러인가요?
- Router 기능이 작동하지 않고 콘솔 오류가 나는 상황

### 에러 메시지
```
setImmediate.js:13 Uncaught ReferenceError: global is not defined
    at node_modules/fbjs/lib/setImmediate.js (setImmediate.js:13:18)
    at require (chunk-RTJ3Z55O.js?v=dbbe1201:11:50)
    at node_modules/draft-js/lib/editOnBeforeInput.js (editOnBeforeInput.js:27:20)
    at require (chunk-RTJ3Z55O.js?v=dbbe1201:11:50)
    at node_modules/draft-js/lib/DraftEditorEditHandler.js (DraftEditorEditHandler.js:15:21)
    at require (chunk-RTJ3Z55O.js?v=dbbe1201:11:50)
    at node_modules/draft-js/lib/DraftEditor.react.js (DraftEditor.react.js:36:30)
    at require (chunk-RTJ3Z55O.js?v=dbbe1201:11:50)
    at node_modules/draft-js/lib/Draft.js (Draft.js:28:19)
    at __require (chunk-RTJ3Z55O.js?v=dbbe1201:11:50)
```

### 에러 핸들링 방법
- 추가한 Register 컴포넌트에 문제가 있음을 확인
- Register 컴포넌트에 연결된 TestEditorForm.jsx가 문제가 있음을 확인
- TestEditorForm.jsx 내부의 editor라는 모듈이 설치되어있었음

**Comment by ToyCon** [comment]
오류 원인
- draft-js, react-draft-wysiwyg 두 모듈이 아주 오래된 모듈이어서 globalThis 선언을 필요로 했음

해결 방법
- index.html 파일에
<script>
  const global = globalThis;
</script>
추가
